
engines:

  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
    config:
      extensions:
      - .js
    ratings:
      paths:
      - src/**
      - __tests__/**
      - "**.js"
      - "**.yml"

  duplication:
    enabled: false
    config:
      languages:
      - javascript
