# Basic Travis configuration.
sudo: false
language: node_js
node_js:
  - 11

env:
  global:
    - CC_TEST_REPORTER_ID=99872bea060a2810f820cc6764910bbabd9b1ac561b01750f5bea600d7f17923

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  - npx eslint src __tests__

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
