# Basic Travis configuration.
sudo: false
language: node_js
node_js:
  - 11

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  - npx eslint client __tests__

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
